version: '3'

services:
  postgres_db:
    image: postgres:latest
    container_name: postgres_db
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: abc123
    volumes:
      - postgres_data:/var/lib/mysql
    networks:
      - node-network

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    networks:
      - node-network

  api:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - NODE_ENV=development
    depends_on:
      - postgres_db
    links:
      - postgres_db
    environment:
      PORT: 3000
    ports:
      - '3000:3000'
    volumes:
      - .:/app
      - /app/node_modules
    command: >
      npm run start:dev
    networks:
      - node-network

volumes:
  # for persistence between restarts
  postgres_data:

networks:
  node-network:
    driver: bridge
